#' Trex Matrix Interface
#'
#' This function runs the Trex algorithm to generate latent vectors from
#' input data. The output can be returned as a matrix, with options to choose
#' between deep learning autoencoders or geometric transformations.
#'
#' @examples
#' # Get Data
#' data("trex_example")
#'
#' # Using the encoder method with a variational autoencoder
#' trex_values <- Trex_matrix(trex_example,
#'     chain = "TRA",
#'     method = "encoder",
#'     encoder.model = "VAE",
#'     encoder.input = "atchleyFactors"
#' )
#'
#' # Using the geometric method with a specified angle
#' trex_values <- Trex_matrix(trex_example,
#'     chain = "TRB",
#'     method = "geometric",
#'     geometric.theta = pi
#' )
#'
#' @param input.data Input data, which can be:
#'   \itemize{
#'     \item A single-cell object in Seurat or SingleCellExperiment format
#'     \item The output of \code{\link[scRepertoire]{combineTCR}}
#'   }
#' @param chain Character. Specifies which TCR chain to analyze:
#'   \itemize{
#'     \item \code{"TRA"}: T cell receptor alpha chain
#'     \item \code{"TRB"}: T cell receptor beta chain
#'   }
#' @param method Character. The algorithm to use for generating latent vectors:
#'   \itemize{
#'     \item \code{"encoder"}: Uses deep learning autoencoders
#'     \item \code{"geometric"}: Uses geometric transformations
#'   }
#' @param encoder.model Character. The type of autoencoder model to use
#'   (only when \code{method = "encoder"}):
#'   \itemize{
#'     \item \code{"VAE"}: Variational autoencoder
#'     \item \code{"AE"}: Dense autoencoder
#'   }
#' @param encoder.input Character. Specifies the input features for the
#'   encoder model. Options include:
#'   \itemize{
#'     \item Amino acid properties: \code{"atchleyFactors"},
#'       \code{"kideraFactors"}
#'     \item \code{"OHE"}: One-hot encoding
#'   }
#' @param geometric.method Character or matrix. The substitution matrix to use
#'   for geometric encoding. Can be:
#'   \itemize{
#'     \item A character string specifying a built-in matrix (e.g.,
#'       \code{"BLOSUM62"}, \code{"BLOSUM45"}, \code{"PAM250"})
#'     \item A custom 20x20 numeric matrix with amino acid row/column names
#'   }
#'   Default is \code{"BLOSUM62"}.
#' @param geometric.theta Numeric. Angle (in radians) for the geometric
#'   transformation. Only used when \code{method = "geometric"}.
#'   Default is \code{pi}.
#' @param verbose Logical. Whether to print progress messages. Default is
#'   \code{TRUE}.
#'
#' @return A data frame of latent vectors generated by the specified method,
#'   with cells as rows and embedding dimensions as columns.
#'
#' @export
#' @importFrom basilisk basiliskRun
#' @importFrom immApex propertyEncoder onehotEncoder geometricEncoder
#'
#' @seealso
#' \code{\link{runTrex}} for integration with single-cell objects;
#' \code{\link[immApex]{propertyEncoder}};
#' \code{\link[immApex]{geometricEncoder}}
Trex_matrix <- function(input.data,
                        chain = c("TRA", "TRB"),
                        method = c("encoder", "geometric"),
                        encoder.model = c("VAE", "AE"),
                        encoder.input = c("atchleyFactors", "kideraFactors", "OHE"),
                        geometric.method = "BLOSUM62",
                        geometric.theta = pi,
                        verbose = TRUE) {
    # Match arguments for validation
    chain <- match.arg(chain)
    method <- match.arg(method)

    if (method == "encoder") {
        encoder.model <- match.arg(encoder.model)
        encoder.input <- match.arg(encoder.input)
    }

    # Get TCR sequences
    TCR <- getTCR(input.data, chain)
    membership <- TCR[[1]]

    # Ensure sequences meet length criteria
    checkLength(membership)

    # Get unique barcodes and their sequences
    cells <- unique(membership[, "barcode"])
    sequences <- membership$cdr3_aa[match(cells, membership$barcode)]

    # Handle NA sequences
    valid_idx <- !is.na(sequences)
    valid_sequences <- sequences[valid_idx]

    if (length(valid_sequences) == 0) {
        stop("No valid CDR3 sequences found in the input data.")
    }

    if (method == "encoder") {
        if (verbose) message("Encoding sequences...")

        # Map encoder.input names for model loading
        model_input <- switch(encoder.input,
            "atchleyFactors" = "AF",
            "kideraFactors" = "KF",
            "OHE" = "OHE"
        )

        # Encode sequences using immApex
        if (encoder.input == "OHE") {
            encoded <- suppressMessages(onehotEncoder(
                input.sequences = valid_sequences,
                max.length = 60,
                convert.to.matrix = TRUE,
                padding.symbol = ".",
                verbose = FALSE
            ))
            encoded_values <- encoded[[2]]
        } else {
            encoded <- suppressMessages(propertyEncoder(
                input.sequences = valid_sequences,
                max.length = 60,
                property.set = encoder.input,
                convert.to.matrix = TRUE,
                verbose = FALSE
            ))
            encoded_values <- encoded[[2]]
        }

        if (verbose) message("Calculating latent dimensions...")

        # Load model
        model_path <- aa.model.loader(chain, model_input, encoder.model)

        # Run prediction through basilisk
        reduction <- basiliskRun(
            env = trex_env,
            fun = function(mpath, xmat) {
                keras <- reticulate::import("keras", delay_load = FALSE)
                model <- NULL
                pred <- NULL

                tryCatch(
                    {
                        model <- keras$models$load_model(mpath)
                        pred <- model$predict(xmat, verbose = 0L)
                        as.array(pred)
                    },
                    finally = {
                        rm(pred)
                        rm(model)
                        keras$backend$clear_session()
                        gc()
                    }
                )
            },
            mpath = model_path,
            xmat = encoded_values
        )
    } else if (method == "geometric") {
        if (verbose) message("Performing geometric transformation...")

        reduction <- suppressMessages(geometricEncoder(
            input.sequences = valid_sequences,
            method = geometric.method,
            theta = geometric.theta,
            verbose = FALSE
        ))[[3]]
    }

    # Create full result matrix with zeros for NA sequences
    full_reduction <- matrix(0, nrow = length(cells), ncol = ncol(reduction))
    full_reduction[valid_idx, ] <- as.matrix(reduction)

    # Format output
    reduction <- as.data.frame(full_reduction)
    rownames(reduction) <- cells
    colnames(reduction) <- paste0("Trex_", seq_len(ncol(reduction)))

    return(reduction)
}
